### ISSUE TITLE
Strange FileReferenceExpiredError when accessing data file

### ISSUE THREAD

**Issue by Gowee** [Gowee/telegram-user-tracker#2]
After roughly 6 months of running, the data file gets expired somehow automatically, preventing the bot to access it at all. 

Log:
```
[ INFO/2021-07-26 02:19:34,702] telethon.client.downloads: Starting direct file download in chunks of 131072 at 0, stride 131072
[WARNING/2021-07-26 02:19:34,774] telegram_user_tracker.core: Error when check_and_report
Traceback (most recent call last):
  File "/app/telegram_user_tracker/core.py", line 215, in keep_tracking
    await check_and_report()
  File "/app/telegram_user_tracker/core.py", line 229, in check_and_report
    d = await blockedUsersStorage.load()
  File "/app/telegram_user_tracker/storage.py", line 67, in load
    d = await client.download_media(self.message, bytes)
  File "/usr/local/lib/python3.9/site-packages/telethon/client/downloads.py", line 397, in download_media
    return await self._download_document(
  File "/usr/local/lib/python3.9/site-packages/telethon/client/downloads.py", line 849, in _download_document
    result = await self._download_file(
  File "/usr/local/lib/python3.9/site-packages/telethon/client/downloads.py", line 520, in _download_file
    async for chunk in self._iter_download(
  File "/usr/local/lib/python3.9/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/usr/local/lib/python3.9/site-packages/telethon/client/downloads.py", line 62, in _load_next_chunk
    cur = await self._request()
  File "/usr/local/lib/python3.9/site-packages/telethon/client/downloads.py", line 72, in _request
    result = await self.client._call(self._sender, self.request)
  File "/usr/local/lib/python3.9/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.FileReferenceExpiredError: The file reference has expired and is no longer valid or it belongs to self-destructing media and cannot be resent (caused by GetFileRequest)
```

Possible fix:
Re-create the data file by sending a new message so that to keep it fresh.

Manual fix:
Download the file with tags prefixed with `#message_storage` and re-send them with tags kept intact. The bot will pick the latest file by tags automatically.

**Comment by Gowee** [comment]
+ TODO: Log the date of the data storage message when initializing.

**Comment by Gowee** [comment]
Update: 

The error seems fairly more complicated than what is expected at first. Even though a fresh message is used, the server returns such error sometimes.

**Comment by Gowee** [comment]
Update:
The problem appears to be fixed by preparing the message for storage (i.e.  searching it by key) before accessing it every time.
