### ISSUE TITLE
telethon failed to parse previously stored binary data after upgrading

### ISSUE THREAD

**Issue by Gowee** [Gowee/telegram-user-tracker#3]
```
[ INFO/2021-08-11 09:24:59,986] telegram_user_tracker.core: Tracker is checking
[WARNING/2021-08-11 09:25:00,093] telegram_user_tracker.core: Error when check_and_report
Traceback (most recent call last):
  File "/home/lotus/Workspace/telegram-user-tracker/telegram_user_tracker/core.py", line 223, in keep_tracking
    await check_and_report()
  File "/home/lotus/Workspace/telegram-user-tracker/telegram_user_tracker/core.py", line 241, in check_and_report
    previous_blocked = {user.id: user for user in deserialize_vector(d)}
  File "/home/lotus/Workspace/telegram-user-tracker/telegram_user_tracker/utils.py", line 43, in deserialize_vector
    return BinaryReader(vector).tgread_vector()
  File "/home/lotus/Workspace/telegram-user-tracker/.venv/lib/python3.9/site-packages/telethon/extensions/binaryreader.py", line 150, in tgread_vector
    return [self.tgread_object() for _ in range(count)]
  File "/home/lotus/Workspace/telegram-user-tracker/.venv/lib/python3.9/site-packages/telethon/extensions/binaryreader.py", line 150, in <listcomp>
    return [self.tgread_object() for _ in range(count)]
  File "/home/lotus/Workspace/telegram-user-tracker/.venv/lib/python3.9/site-packages/telethon/extensions/binaryreader.py", line 142, in tgread_object
    return clazz.from_reader(self)
  File "/home/lotus/Workspace/telegram-user-tracker/telegram_user_tracker/contacts.py", line 47, in from_reader
    user = super().from_reader(reader)
  File "/home/lotus/Workspace/telegram-user-tracker/.venv/lib/python3.9/site-packages/telethon/tl/types/__init__.py", line 27806, in from_reader
    _photo = reader.tgread_object()
  File "/home/lotus/Workspace/telegram-user-tracker/.venv/lib/python3.9/site-packages/telethon/extensions/binaryreader.py", line 140, in tgread_object
    raise error
telethon.errors.common.TypeNotFoundError: Could not find a matching Constructor ID for the TLObject that was supposed to be read with ID 69d3ab26. Most likely, a TLObject was trying to be read when it should not be read. Remaining bytes: 
```

**Comment by Gowee** [comment]
Partially fixed by 31bdf368adaffbe1e059e9767d74f41e408065ed. 

Just use SQLite instead?
